//
//  LanguageManager.swift
//  Swift Zip Manager For iOS
//
//  Created by Haoran on 2026/5/10.
//

import SwiftUI
import Combine

class LanguageManager: ObservableObject {
    @Published var currentLanguage: String = "en"
    
    let supportedLanguages: [String: String] = [
        "en": "English",
        "zh-Hans": "简体中文",
        "zh-Hant": "繁體中文",
        "ja": "日本語",
        "ko": "한국어",
        "fr": "Français",
        "de": "Deutsch",
        "es": "Español",
        "it": "Italiano",
        "pt": "Português",
        "ru": "Русский",
        "ar": "العربية",
        "tr": "Türkçe",
        "vi": "Tiếng Việt"
    ]
    
    init() {
        if let preferredLang = Locale.preferredLanguages.first {
            let langCode = String(preferredLang.prefix(2))
            if supportedLanguages.keys.contains(where: { $0.hasPrefix(langCode) }) {
                currentLanguage = supportedLanguages.keys.first { $0.hasPrefix(langCode) } ?? "en"
            }
        }
        
        if let savedLang = UserDefaults.standard.string(forKey: "AppLanguage"),
           supportedLanguages.keys.contains(savedLang) {
            currentLanguage = savedLang
        }
    }
    
    func setLanguage(_ language: String) {
        currentLanguage = language
        UserDefaults.standard.set(language, forKey: "AppLanguage")
        UserDefaults.standard.synchronize()
    }
    
    func localizedString(_ key: String) -> String {
        return LocalizationService.shared.localizedString(key, language: currentLanguage)
    }
}

// MARK: - Localization Service
class LocalizationService {
    static let shared = LocalizationService()
    
    private let translations: [String: [String: String]] = [
        // English
        "en": [
            "files": "Files",
            "archives": "Archives",
            "settings": "Settings",
            "empty_folder": "Empty Folder",
            "no_archive": "No Archive Open",
            "open_archive": "Open Archive",
            "new_archive": "New Archive",
            "extract": "Extract",
            "extract_all": "Extract All",
            "close": "Close",
            "cancel": "Cancel",
            "create": "Create",
            "delete": "Delete",
            "share": "Share",
            "rename": "Rename",
            "language": "Language",
            "about": "About",
            "version": "Version",
            "general": "General",
            "items": "items",
            "name": "Name",
            "size": "Size",
            "modified": "Modified",
            "archive_info": "Archive Info",
            "format": "Format",
            "destination": "Destination",
            "add_files": "Add Files",
            "choose_folder": "Choose Folder",
            "extract_to": "Extract to",
            "create_archive": "Create Archive",
            "extracting": "Extracting...",
            "creating": "Creating...",
            "extract_complete": "Extract Complete",
            "archive_created": "Archive Created",
            "ok": "OK",
            "done": "Done"
        ],
        
        // Simplified Chinese
        "zh-Hans": [
            "files": "文件",
            "archives": "压缩包",
            "settings": "设置",
            "empty_folder": "文件夹为空",
            "no_archive": "未打开压缩包",
            "open_archive": "打开压缩包",
            "new_archive": "新建压缩包",
            "extract": "解压",
            "extract_all": "解压全部",
            "close": "关闭",
            "cancel": "取消",
            "create": "创建",
            "delete": "删除",
            "share": "分享",
            "rename": "重命名",
            "language": "语言",
            "about": "关于",
            "version": "版本",
            "general": "通用",
            "items": "个项目",
            "name": "名称",
            "size": "大小",
            "modified": "修改日期",
            "archive_info": "压缩包信息",
            "format": "格式",
            "destination": "目标位置",
            "add_files": "添加文件",
            "choose_folder": "选择文件夹",
            "extract_to": "解压到",
            "create_archive": "创建压缩包",
            "extracting": "正在解压...",
            "creating": "正在创建...",
            "extract_complete": "解压完成",
            "archive_created": "压缩包已创建",
            "ok": "确定",
            "done": "完成"
        ],
        
        // Traditional Chinese
        "zh-Hant": [
            "files": "檔案",
            "archives": "壓縮檔",
            "settings": "設定",
            "empty_folder": "資料夾為空",
            "no_archive": "未開啟壓縮檔",
            "open_archive": "開啟壓縮檔",
            "new_archive": "新增壓縮檔",
            "extract": "解壓縮",
            "extract_all": "解壓縮全部",
            "close": "關閉",
            "cancel": "取消",
            "create": "建立",
            "delete": "刪除",
            "share": "分享",
            "rename": "重新命名",
            "language": "語言",
            "about": "關於",
            "version": "版本",
            "general": "一般",
            "items": "個項目",
            "name": "名稱",
            "size": "大小",
            "modified": "修改日期",
            "archive_info": "壓縮檔資訊",
            "format": "格式",
            "destination": "目標位置",
            "add_files": "加入檔案",
            "choose_folder": "選擇資料夾",
            "extract_to": "解壓縮到",
            "create_archive": "建立壓縮檔",
            "extracting": "正在解壓縮...",
            "creating": "正在建立...",
            "extract_complete": "解壓縮完成",
            "archive_created": "壓縮檔已建立",
            "ok": "確定",
            "done": "完成"
        ],
        
        // Japanese
        "ja": [
            "files": "ファイル",
            "archives": "アーカイブ",
            "settings": "設定",
            "empty_folder": "空のフォルダ",
            "no_archive": "アーカイブが開かれていません",
            "open_archive": "アーカイブを開く",
            "new_archive": "新規アーカイブ",
            "extract": "解凍",
            "extract_all": "すべて解凍",
            "close": "閉じる",
            "cancel": "キャンセル",
            "create": "作成",
            "delete": "削除",
            "share": "共有",
            "rename": "名前を変更",
            "language": "言語",
            "about": "情報",
            "version": "バージョン",
            "general": "一般",
            "items": "項目",
            "name": "名前",
            "size": "サイズ",
            "modified": "更新日",
            "archive_info": "アーカイブ情報",
            "format": "形式",
            "destination": "保存先",
            "add_files": "ファイルを追加",
            "choose_folder": "フォルダを選択",
            "extract_to": "解凍先",
            "create_archive": "アーカイブを作成",
            "extracting": "解凍中...",
            "creating": "作成中...",
            "extract_complete": "解凍完了",
            "archive_created": "アーカイブを作成しました",
            "ok": "OK",
            "done": "完了"
        ],
        
        // Korean
        "ko": [
            "files": "파일",
            "archives": "아카이브",
            "settings": "설정",
            "empty_folder": "빈 폴더",
            "no_archive": "열린 아카이브 없음",
            "open_archive": "아카이브 열기",
            "new_archive": "새 아카이브",
            "extract": "압축 풀기",
            "extract_all": "모두 압축 풀기",
            "close": "닫기",
            "cancel": "취소",
            "create": "만들기",
            "delete": "삭제",
            "share": "공유",
            "rename": "이름 바꾸기",
            "language": "언어",
            "about": "정보",
            "version": "버전",
            "general": "일반",
            "items": "개 항목",
            "name": "이름",
            "size": "크기",
            "modified": "수정일",
            "archive_info": "아카이브 정보",
            "format": "형식",
            "destination": "대상",
            "add_files": "파일 추가",
            "choose_folder": "폴더 선택",
            "extract_to": "압축 풀 위치",
            "create_archive": "아카이브 만들기",
            "extracting": "압축 푸는 중...",
            "creating": "만드는 중...",
            "extract_complete": "압축 풀기 완료",
            "archive_created": "아카이브 생성됨",
            "ok": "확인",
            "done": "완료"
        ],
        
        // French
        "fr": [
            "files": "Fichiers",
            "archives": "Archives",
            "settings": "Paramètres",
            "empty_folder": "Dossier vide",
            "no_archive": "Aucune archive ouverte",
            "open_archive": "Ouvrir une archive",
            "new_archive": "Nouvelle archive",
            "extract": "Extraire",
            "extract_all": "Tout extraire",
            "close": "Fermer",
            "cancel": "Annuler",
            "create": "Créer",
            "delete": "Supprimer",
            "share": "Partager",
            "rename": "Renommer",
            "language": "Langue",
            "about": "À propos",
            "version": "Version",
            "general": "Général",
            "items": "éléments",
            "name": "Nom",
            "size": "Taille",
            "modified": "Modifié",
            "archive_info": "Info archive",
            "format": "Format",
            "destination": "Destination",
            "add_files": "Ajouter fichiers",
            "choose_folder": "Choisir dossier",
            "extract_to": "Extraire vers",
            "create_archive": "Créer archive",
            "extracting": "Extraction...",
            "creating": "Création...",
            "extract_complete": "Extraction terminée",
            "archive_created": "Archive créée",
            "ok": "OK",
            "done": "Terminé"
        ],
        
        // German
        "de": [
            "files": "Dateien",
            "archives": "Archive",
            "settings": "Einstellungen",
            "empty_folder": "Leerer Ordner",
            "no_archive": "Kein Archiv geöffnet",
            "open_archive": "Archiv öffnen",
            "new_archive": "Neues Archiv",
            "extract": "Entpacken",
            "extract_all": "Alle entpacken",
            "close": "Schließen",
            "cancel": "Abbrechen",
            "create": "Erstellen",
            "delete": "Löschen",
            "share": "Teilen",
            "rename": "Umbenennen",
            "language": "Sprache",
            "about": "Über",
            "version": "Version",
            "general": "Allgemein",
            "items": "Elemente",
            "name": "Name",
            "size": "Größe",
            "modified": "Geändert",
            "archive_info": "Archivinfo",
            "format": "Format",
            "destination": "Ziel",
            "add_files": "Dateien hinzufügen",
            "choose_folder": "Ordner wählen",
            "extract_to": "Entpacken nach",
            "create_archive": "Archiv erstellen",
            "extracting": "Entpacke...",
            "creating": "Erstelle...",
            "extract_complete": "Entpacken abgeschlossen",
            "archive_created": "Archiv erstellt",
            "ok": "OK",
            "done": "Fertig"
        ],
        
        // Spanish
        "es": [
            "files": "Archivos",
            "archives": "Archivos",
            "settings": "Ajustes",
            "empty_folder": "Carpeta vacía",
            "no_archive": "Ningún archivo abierto",
            "open_archive": "Abrir archivo",
            "new_archive": "Nuevo archivo",
            "extract": "Extraer",
            "extract_all": "Extraer todo",
            "close": "Cerrar",
            "cancel": "Cancelar",
            "create": "Crear",
            "delete": "Eliminar",
            "share": "Compartir",
            "rename": "Renombrar",
            "language": "Idioma",
            "about": "Acerca de",
            "version": "Versión",
            "general": "General",
            "items": "elementos",
            "name": "Nombre",
            "size": "Tamaño",
            "modified": "Modificado",
            "archive_info": "Info del archivo",
            "format": "Formato",
            "destination": "Destino",
            "add_files": "Añadir archivos",
            "choose_folder": "Elegir carpeta",
            "extract_to": "Extraer a",
            "create_archive": "Crear archivo",
            "extracting": "Extrayendo...",
            "creating": "Creando...",
            "extract_complete": "Extracción completa",
            "archive_created": "Archivo creado",
            "ok": "OK",
            "done": "Hecho"
        ],
        
        // Italian
        "it": [
            "files": "File",
            "archives": "Archivi",
            "settings": "Impostazioni",
            "empty_folder": "Cartella vuota",
            "no_archive": "Nessun archive aperto",
            "open_archive": "Apri archive",
            "new_archive": "Nuovo archive",
            "extract": "Estrai",
            "extract_all": "Estrai tutto",
            "close": "Chiudi",
            "cancel": "Annulla",
            "create": "Crea",
            "delete": "Elimina",
            "share": "Condividi",
            "rename": "Rinomina",
            "language": "Lingua",
            "about": "Informazioni",
            "version": "Versione",
            "general": "Generale",
            "items": "elementi",
            "name": "Nome",
            "size": "Dimensione",
            "modified": "Modificato",
            "archive_info": "Info archive",
            "format": "Formato",
            "destination": "Destinazione",
            "add_files": "Aggiungi file",
            "choose_folder": "Scegli cartella",
            "extract_to": "Estrai in",
            "create_archive": "Crea archive",
            "extracting": "Estrazione...",
            "creating": "Creazione...",
            "extract_complete": "Estrazione completata",
            "archive_created": "Archive creato",
            "ok": "OK",
            "done": "Fatto"
        ],
        
        // Portuguese
        "pt": [
            "files": "Arquivos",
            "archives": "Arquivos",
            "settings": "Configurações",
            "empty_folder": "Pasta vazia",
            "no_archive": "Nenhum arquivo aberto",
            "open_archive": "Abrir arquivo",
            "new_archive": "Novo arquivo",
            "extract": "Extrair",
            "extract_all": "Extrair tudo",
            "close": "Fechar",
            "cancel": "Cancelar",
            "create": "Criar",
            "delete": "Excluir",
            "share": "Compartilhar",
            "rename": "Renomear",
            "language": "Idioma",
            "about": "Sobre",
            "version": "Versão",
            "general": "Geral",
            "items": "itens",
            "name": "Nome",
            "size": "Tamanho",
            "modified": "Modificado",
            "archive_info": "Info do arquivo",
            "format": "Formato",
            "destination": "Destino",
            "add_files": "Adicionar arquivos",
            "choose_folder": "Escolher pasta",
            "extract_to": "Extrair para",
            "create_archive": "Criar arquivo",
            "extracting": "Extraindo...",
            "creating": "Criando...",
            "extract_complete": "Extração concluída",
            "archive_created": "Arquivo criado",
            "ok": "OK",
            "done": "Concluído"
        ],
        
        // Russian
        "ru": [
            "files": "Файлы",
            "archives": "Архивы",
            "settings": "Настройки",
            "empty_folder": "Пустая папка",
            "no_archive": "Архив не открыт",
            "open_archive": "Открыть архив",
            "new_archive": "Новый архив",
            "extract": "Извлечь",
            "extract_all": "Извлечь всё",
            "close": "Закрыть",
            "cancel": "Отмена",
            "create": "Создать",
            "delete": "Удалить",
            "share": "Поделиться",
            "rename": "Переименовать",
            "language": "Язык",
            "about": "О программе",
            "version": "Версия",
            "general": "Основные",
            "items": "элементов",
            "name": "Имя",
            "size": "Размер",
            "modified": "Изменён",
            "archive_info": "Информация об архиве",
            "format": "Формат",
            "destination": "Назначение",
            "add_files": "Добавить файлы",
            "choose_folder": "Выбрать папку",
            "extract_to": "Извлечь в",
            "create_archive": "Создать архив",
            "extracting": "Извлечение...",
            "creating": "Создание...",
            "extract_complete": "Извлечение завершено",
            "archive_created": "Архив создан",
            "ok": "ОК",
            "done": "Готово"
        ],
        
        // Arabic
        "ar": [
            "files": "الملفات",
            "archives": "الأرشيفات",
            "settings": "الإعدادات",
            "empty_folder": "مجلد فارغ",
            "no_archive": "لا يوجد أرشيف مفتوح",
            "open_archive": "فتح أرشيف",
            "new_archive": "أرشيف جديد",
            "extract": "استخراج",
            "extract_all": "استخراج الكل",
            "close": "إغلاق",
            "cancel": "إلغاء",
            "create": "إنشاء",
            "delete": "حذف",
            "share": "مشاركة",
            "rename": "إعادة تسمية",
            "language": "اللغة",
            "about": "حول",
            "version": "الإصدار",
            "general": "عام",
            "items": "عناصر",
            "name": "الاسم",
            "size": "الحجم",
            "modified": "تاريخ التعديل",
            "archive_info": "معلومات الأرشيف",
            "format": "الصيغة",
            "destination": "الوجهة",
            "add_files": "إضافة ملفات",
            "choose_folder": "اختر مجلداً",
            "extract_to": "استخراج إلى",
            "create_archive": "إنشاء أرشيف",
            "extracting": "جاري الاستخراج...",
            "creating": "جاري الإنشاء...",
            "extract_complete": "اكتمل الاستخراج",
            "archive_created": "تم إنشاء الأرشيف",
            "ok": "حسنا",
            "done": "تم"
        ],
        
        // Turkish
        "tr": [
            "files": "Dosyalar",
            "archives": "Arşivler",
            "settings": "Ayarlar",
            "empty_folder": "Boş klasör",
            "no_archive": "Açık arşiv yok",
            "open_archive": "Arşiv aç",
            "new_archive": "Yeni arşiv",
            "extract": "Çıkar",
            "extract_all": "Tümünü çıkar",
            "close": "Kapat",
            "cancel": "İptal",
            "create": "Oluştur",
            "delete": "Sil",
            "share": "Paylaş",
            "rename": "Yeniden adlandır",
            "language": "Dil",
            "about": "Hakkında",
            "version": "Sürüm",
            "general": "Genel",
            "items": "öğe",
            "name": "İsim",
            "size": "Boyut",
            "modified": "Değiştirilme",
            "archive_info": "Arşiv bilgisi",
            "format": "Biçim",
            "destination": "Hedef",
            "add_files": "Dosya ekle",
            "choose_folder": "Klasör seç",
            "extract_to": "Çıkarılacak yer",
            "create_archive": "Arşiv oluştur",
            "extracting": "Çıkarılıyor...",
            "creating": "Oluşturuluyor...",
            "extract_complete": "Çıkarma tamamlandı",
            "archive_created": "Arşiv oluşturuldu",
            "ok": "Tamam",
            "done": "Bitti"
        ],
        
        // Vietnamese
        "vi": [
            "files": "Tập tin",
            "archives": "Kho nén",
            "settings": "Cài đặt",
            "empty_folder": "Thư mục trống",
            "no_archive": "Chưa mở kho nén",
            "open_archive": "Mở kho nén",
            "new_archive": "Kho nén mới",
            "extract": "Giải nén",
            "extract_all": "Giải nén tất cả",
            "close": "Đóng",
            "cancel": "Hủy",
            "create": "Tạo",
            "delete": "Xóa",
            "share": "Chia sẻ",
            "rename": "Đổi tên",
            "language": "Ngôn ngữ",
            "about": "Giới thiệu",
            "version": "Phiên bản",
            "general": "Chung",
            "items": "mục",
            "name": "Tên",
            "size": "Kích thước",
            "modified": "Sửa đổi",
            "archive_info": "Thông tin kho nén",
            "format": "Định dạng",
            "destination": "Đích đến",
            "add_files": "Thêm tập tin",
            "choose_folder": "Chọn thư mục",
            "extract_to": "Giải nén đến",
            "create_archive": "Tạo kho nén",
            "extracting": "Đang giải nén...",
            "creating": "Đang tạo...",
            "extract_complete": "Giải nén hoàn tất",
            "archive_created": "Đã tạo kho nén",
            "ok": "OK",
            "done": "Xong"
        ]
    ]
    
    func localizedString(_ key: String, language: String) -> String {
        let langCode = String(language.prefix(2))
        
        if let translation = translations[language]?[key] {
            return translation
        }
        
        if let translation = translations[langCode]?[key] {
            return translation
        }
        
        return translations["en"]?[key] ?? key
    }
}

// MARK: - String Extension
extension String {
    func localized(with manager: LanguageManager) -> String {
        return LocalizationService.shared.localizedString(self, language: manager.currentLanguage)
    }
}
